### ISSUE TITLE
Linux 服务器中加载 Mod 报错

### ISSUE THREAD

**Issue by drsanwujiang** [WJXhhh/KaBlade#1]
在 Linux 服务器中加载 kablade-1.1-b、kablade-1.0-b、kablade-0.9-b、kablade-0.8-b 均会报错并导致服务器崩溃，
抛出的异常为找不到 net/minecraft/client/multiplayer/WorldClient这个类。

具体看了一下，问题出在：
[https://github.com/WJXhhh/KaBlade/blob/master/src/main/java/com/wjx/kablade/Main.java#L149](https://github.com/WJXhhh/KaBlade/blob/master/src/main/java/com/wjx/kablade/Main.java#L149)

猜测是服务端无法注册客户端消息所导致？不知道有没有修复的计划~

**Comment by WJXhhh** [comment]
s

> 在 Linux 服务器中加载 kablade-1.1-b、kablade-1.0-b、kablade-0.9-b、kablade-0.8-b 均会报错并导致服务器崩溃， 抛出的异常为找不到 net/minecraft/client/multiplayer/WorldClient这个类。
> 
> 具体看了一下，问题出在： https://github.com/WJXhhh/KaBlade/blob/master/src/main/java/com/wjx/kablade/Main.java#L149
> 
> 猜测是服务端无法注册客户端消息所导致？不知道有没有修复的计划~

事实上应该不是，这个东西我觉得应该必须在服务端注册，现在跑去问人了

**Comment by WJXhhh** [comment]
感谢反馈，已于1.2-b修复。
