### ISSUE TITLE
游戏崩溃

### ISSUE THREAD

**Issue by GeneralKolchak** [WJXhhh/KaBlade#2]
代码第42行event.getSource().getTrueSource()强制转型转成了EntityLivingBase，导致游戏崩溃，可以加上个判断，if(event.getSource().getTrueSource() instanceof EntityLivingBase)，希望能修复一下

**Comment by Kasualix** [comment]
补：https://github.com/WJXhhh/KaBlade/blob/6df73870726b92d50f9669a855da5929a901f069/src/main/java/com/wjx/kablade/SlashBlade/SpeacialEffects/SEPhoenix.java#L42

**Comment by WJXhhh** [comment]
感谢反馈，已于1.2-b修复。
